version: '3.5'

services:
  routingcore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROVIDER_DNS_NAME: localhost
        PROVIDER_DNS_PORT: 8080
    stdin_open: true
    tty: true
    ports:
    - "8080:8080"