version: '3.5'

services:
  routingcore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROVIDER_ORGANIZATION: BigKoalas
        PROVIDER_ID: BigKoalas-NewChargingStationProvider
        PROVIDER_SECRET: jS_B924KSFagXMB9M7sQhw==
        PROVIDER_DNS_NAME: 35.227.112.7
        PROVIDER_DNS_PORT: 8080
    stdin_open: true
    tty: true
    ports:
    - "8080:8080"