version: '3.5'

services:
  routingcore:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROVIDER_ORGANIZATION: MyOrg
        PROVIDER_ID: MyOrg-MyProvider
        PROVIDER_SECRET: 5TmQYZgdTDWGm6W4C3TUvA==
        PROVIDER_DNS_NAME: https://35.227.112.7/
        PROVIDER_DNS_PORT: 8080
    stdin_open: true
    tty: true
    ports:
    - "8080:8080"